"use client";

import { Badge } from "@/components/ui/Badge";
import type { IntelligenceReport } from "@/types";

interface ReportViewerProps {
  report: IntelligenceReport;
  onClose: () => void;
}

export function ReportViewer({ report, onClose }: ReportViewerProps) {
  return (
    <div className="fixed inset-0 z-50 flex items-start justify-end" role="dialog">
      {/* Backdrop */}
      <div className="absolute inset-0 bg-black/40 backdrop-blur-sm" style={{ animation: "fadeIn 200ms ease-out" }} onClick={onClose} />

      {/* Sheet */}
      <div
        className="relative ml-auto flex h-full w-full max-w-lg flex-col border-l border-slate-200 bg-white shadow-xl dark:border-slate-700 dark:bg-slate-900"
        style={{ animation: "slideIn 200ms var(--ease-out)" }}
      >
        {/* Header */}
        <div className="flex items-center justify-between border-b border-slate-200 px-5 py-4 dark:border-slate-700">
          <div>
            <h2 className="text-sm font-semibold text-slate-900 dark:text-slate-100">{report.topic}</h2>
            <p className="mt-0.5 text-xs text-slate-500 dark:text-slate-400">
              {new Date(report.created_at).toLocaleString()}
            </p>
          </div>
          <button
            onClick={onClose}
            className="rounded-md p-1.5 text-slate-400 hover:bg-slate-100 hover:text-slate-600 dark:hover:bg-slate-800 dark:hover:text-slate-300 transition-colors duration-150"
          >
            <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" strokeWidth={1.5}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-5">
          <div className="prose prose-sm dark:prose-invert max-w-none">
            <p className="text-sm leading-relaxed text-slate-600 dark:text-slate-400">
              This report is generated by the intelligence pipeline. Full content will appear once the report generation workflow is connected.
            </p>

            <div className="mt-6 rounded-lg border border-slate-200 bg-slate-50 p-4 dark:border-slate-700 dark:bg-slate-800/50">
              <h4 className="text-xs font-medium uppercase tracking-wide text-slate-500 dark:text-slate-400 mb-2">Metadata</h4>
              <dl className="grid grid-cols-2 gap-x-4 gap-y-2 text-xs">
                <dt className="text-slate-500 dark:text-slate-400">Topic</dt>
                <dd className="text-slate-900 dark:text-slate-100">{report.topic}</dd>

                <dt className="text-slate-500 dark:text-slate-400">ID</dt>
                <dd className="font-mono text-slate-600 dark:text-slate-400">{report.id.slice(0, 12)}…</dd>

                <dt className="text-slate-500 dark:text-slate-400">Created</dt>
                <dd className="text-slate-900 dark:text-slate-100">
                  {new Date(report.created_at).toLocaleDateString(undefined, {
                    month: "short", day: "numeric", year: "numeric", hour: "2-digit", minute: "2-digit",
                  })}
                </dd>
              </dl>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
